# Generated by Django 5.0.1 on 2024-02-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilemodel_meduim_link_profilemodel_pinterest_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='meduim_link',
            new_name='medium_link',
        ),
    ]
