# Generated by Django 5.0.1 on 2024-02-21 21:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_postmodel_content_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=tinymce.models.HTMLField(default='for you guys without content you are safe'),
            preserve_default=False,
        ),
    ]
