# Generated by Django 5.0.1 on 2024-02-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='intro',
            field=models.TextField(default='A default intro of your blog post not more than three sentences for a nice rendering', max_length=255),
            preserve_default=False,
        ),
    ]
